#!/usr/bin/env node
/* Generates order/fallback-store.js: the store snapshot the customer site uses in demo mode
 * when the register has not published one yet (no mogoba.bridge.store key on this origin).
 *
 * The menu comes from www/js/seed.js, run in a node:vm sandbox with a stub window/self, so the
 * fallback never drifts from the register's starting menu. Output follows the store snapshot
 * shape in docs/online-ordering.md. updatedAt is 0 so the file only changes when the menu does.
 *
 *   node tools/gen-store.mjs */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SEED = join(ROOT, 'www', 'js', 'seed.js');
const OUT = join(ROOT, 'order', 'fallback-store.js');

/* seed.js is a classic script that writes window.M.seed. */
const sandbox = { window: {}, Date, Math };
sandbox.self = sandbox.window;
vm.createContext(sandbox);
vm.runInContext(readFileSync(SEED, 'utf8'), sandbox, { filename: 'seed.js' });
const seed = sandbox.window.M && sandbox.window.M.seed;
if (!seed || !Array.isArray(seed.items)) throw new Error('seed.js did not define M.seed.items');

/* Add-on groups are referenced by id on items; the snapshot carries them inline. */
const groups = new Map(seed.MODS.map((g) => [g.id, g]));
const addonGroup = (gid) => {
  const g = groups.get(gid);
  if (!g) throw new Error('Unknown add-on group ' + gid);
  return { gid: g.id, name: g.name, options: g.options.map((o) => ({ id: o.id, name: o.name, price: o.price })) };
};

const cats = [...seed.CATS].sort((a, b) => a.sort - b.sort).map((c) => ({ id: c.id, name: c.name, ko: c.ko || '' }));

const items = seed.items
  .filter((it) => it.active !== false)
  .sort((a, b) => a.sort - b.sort)
  .map((it) => ({
    id: it.id,
    cat: it.cat,
    name: it.name,
    ko: it.ko || '',
    img: it.img || '',
    price: it.price,
    soldOut: false,
    badge: it.badge || '',
    variantLabel: it.variants && it.variants.length ? it.variantLabel || 'Choose' : '',
    variants: (it.variants || []).map((v) => ({ id: v.id, name: v.name, price: v.price, soldOut: false })),
    addons: (it.addons || []).map(addonGroup),
  }));

const store = {
  v: 1,
  updatedAt: 0,
  name: seed.SETTINGS().business.name,
  address: seed.SETTINGS().business.address,
  phone: seed.SETTINGS().business.phone,
  accepting: true,
  hours: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, open: '09:00', close: '20:00' })),
  prepMinutes: 20,
  pickup: { enabled: true },
  delivery: { enabled: true, fee: 5000, minOrder: 30000, area: 'Aparri town proper' },
  /* Placeholders. With no QR the site shows GCash and Maya as "QR not set up yet". */
  payments: {
    gcash: { enabled: true, accountName: 'Mogoba Korean Food House', number: '', qr: '' },
    maya: { enabled: true, accountName: 'Mogoba Korean Food House', number: '', qr: '' },
    cash: { enabled: true },
  },
  cats,
  items,
};

const body =
  '/* Generated by tools/gen-store.mjs from www/js/seed.js. Do not edit by hand.\n' +
  ' * Demo mode store snapshot, used until the register publishes mogoba.bridge.store. */\n' +
  'window.MOGOBA_FALLBACK_STORE = ' +
  JSON.stringify(store, null, 1) +
  ';\n';
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log('order/fallback-store.js: ' + cats.length + ' categories, ' + items.length + ' items, ' + body.length + ' bytes');
