#!/usr/bin/env bash
# apply-cloudflare-dns.sh — create the cold-outreach sending records in Cloudflare.
#
# Why a separate sending identity at all: as of 2026-08-07 all outreach leaves
# on the primary business domain from a single mailbox, with no bounce feedback
# and no warmup. One bad list on that domain costs KQuality its ordinary email,
# not just its outreach. Everything below isolates the outreach reputation.
#
# Usage:
#   export CLOUDFLARE_API_TOKEN=...        # Zone:DNS:Edit on kqualitycleaningservices.com.au
#   export DKIM_VALUE='v=DKIM1; k=rsa; p=...'   # optional, from the sending provider
#   ./apply-cloudflare-dns.sh [--apply]    # dry run without --apply
#
# Idempotent: an existing record with the same name and type is updated, not
# duplicated.
set -euo pipefail

ZONE_NAME="${ZONE_NAME:-kqualitycleaningservices.com.au}"
SUB="${SUB:-outreach}"
FQDN="${SUB}.${ZONE_NAME}"
DMARC_RUA="${DMARC_RUA:-dmarc@${ZONE_NAME}}"
DKIM_SELECTOR="${DKIM_SELECTOR:-google}"
API="https://api.cloudflare.com/client/v4"
APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

: "${CLOUDFLARE_API_TOKEN:?set CLOUDFLARE_API_TOKEN (Zone:DNS:Edit scope)}"
command -v jq >/dev/null || { echo "jq is required"; exit 1; }

cf() { curl -sS -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" "$@"; }

ZONE_ID=$(cf "$API/zones?name=${ZONE_NAME}" | jq -r '.result[0].id // empty')
[ -n "$ZONE_ID" ] || { echo "zone ${ZONE_NAME} not found, or the token cannot see it"; exit 1; }
echo "zone ${ZONE_NAME} = ${ZONE_ID}"

# upsert <type> <name> <content> [priority]
upsert() {
  local type="$1" name="$2" content="$3" prio="${4:-}"
  local existing payload method url
  existing=$(cf "$API/zones/$ZONE_ID/dns_records?type=${type}&name=${name}" | jq -r '.result[0].id // empty')

  if [ -n "$prio" ]; then
    payload=$(jq -nc --arg t "$type" --arg n "$name" --arg c "$content" --argjson p "$prio" \
      '{type:$t,name:$n,content:$c,priority:$p,ttl:3600,proxied:false}')
  else
    payload=$(jq -nc --arg t "$type" --arg n "$name" --arg c "$content" \
      '{type:$t,name:$n,content:$c,ttl:3600,proxied:false}')
  fi

  if [ -n "$existing" ]; then method=PUT;  url="$API/zones/$ZONE_ID/dns_records/$existing"
  else                        method=POST; url="$API/zones/$ZONE_ID/dns_records"; fi

  if [ "$APPLY" -eq 0 ]; then
    printf '  DRY  %-5s %-46s %s\n' "$type" "$name" "${content:0:70}"
    return
  fi
  local out ok
  out=$(cf -X "$method" "$url" --data "$payload")
  ok=$(echo "$out" | jq -r '.success')
  if [ "$ok" = "true" ]; then printf '  OK   %-5s %-46s %s\n' "$type" "$name" "${content:0:70}"
  else printf '  FAIL %-5s %-46s %s\n' "$type" "$name" "$(echo "$out" | jq -c '.errors')"; fi
}

echo
echo "--- receiving: bounces must land somewhere or the circuit breaker is blind ---"
# Google Workspace single-host MX. If the outreach mailbox is on another
# provider, replace this one line with that provider's MX host.
upsert MX "$FQDN" "smtp.google.com" 1

echo
echo "--- SPF: only Google may send as ${FQDN}; everything else is a hard fail ---"
upsert TXT "$FQDN" "v=spf1 include:_spf.google.com -all"

echo
echo "--- DMARC: start at p=none, move to quarantine once reports are clean ---"
upsert TXT "_dmarc.${FQDN}" \
  "v=DMARC1; p=none; sp=none; adkim=r; aspf=r; fo=1; pct=100; rua=mailto:${DMARC_RUA}; ruf=mailto:${DMARC_RUA}"

echo
echo "--- DKIM ---"
if [ -n "${DKIM_VALUE:-}" ]; then
  upsert TXT "${DKIM_SELECTOR}._domainkey.${FQDN}" "$DKIM_VALUE"
else
  echo "  SKIP TXT   ${DKIM_SELECTOR}._domainkey.${FQDN}"
  echo "       DKIM keys are generated by the sending provider, not here."
  echo "       Google Workspace: Admin console > Apps > Google Workspace > Gmail >"
  echo "       Authenticate email > select ${FQDN} > Generate new record (2048-bit),"
  echo "       then re-run with DKIM_VALUE='v=DKIM1; k=rsa; p=...'"
fi

echo
if [ "$APPLY" -eq 0 ]; then
  echo "dry run only. re-run with --apply to write these records."
else
  echo "records applied. before sending anything:"
  echo "  1. verify:  dig +short TXT ${FQDN}; dig +short TXT _dmarc.${FQDN}; dig +short MX ${FQDN}"
  echo "  2. confirm DKIM is signing (send one message to a checker, look for dkim=pass)"
  echo "  3. only then:  UPDATE leads.mailbox SET status='warmup', warmup_started_on=current_date"
  echo "                  WHERE address='michelle@${FQDN}';"
  echo "     10/day on day one, +5/day, hard cap 40. The queue dispatcher enforces it."
fi
